# Generated by Django 2.1.5 on 2019-06-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=120, verbose_name='broker')),
                ('operation_cost_day_trade', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cost Day Trade')),
                ('operation_cost_fraction', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cost Fraction')),
                ('operation_cost_position', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cost Normal')),
                ('equity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='equity')),
                ('next_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
    ]
