# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broker', models.CharField(max_length=120, unique=True, verbose_name='broker')),
                ('operation_cost', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='operation cost')),
                ('equity', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='equity')),
            ],
        ),
    ]
