# Generated by Django 2.0.6 on 2018-07-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_next_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='broker',
            field=models.CharField(max_length=120, verbose_name='broker'),
        ),
    ]
