# Generated by Django 2.0.6 on 2018-07-06 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180702_2105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='operation_cost',
            new_name='operation_cost_position',
        ),
        migrations.AddField(
            model_name='account',
            name='operation_cost_day_trade',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=7, verbose_name='operation cost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='operation_cost_fraction',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=7, verbose_name='operation cost'),
            preserve_default=False,
        ),
    ]
