# Generated by Django 2.0.6 on 2018-10-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180706_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='operation_cost_day_trade',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cost Day Trade'),
        ),
        migrations.AlterField(
            model_name='account',
            name='operation_cost_fraction',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cost Fraction'),
        ),
        migrations.AlterField(
            model_name='account',
            name='operation_cost_position',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Cost Normal'),
        ),
    ]
