# Generated by Django 2.0.6 on 2018-06-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name='Code')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='stock value')),
            ],
        ),
    ]
