# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=22, verbose_name='stock value'),
            preserve_default=False,
        ),
    ]
