# Generated by Django 2.0.6 on 2018-11-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='name',
            field=models.CharField(default='Company', max_length=140, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Sector'),
        ),
        migrations.AddField(
            model_name='stock',
            name='subsector',
            field=models.CharField(blank=True, max_length=140, null=True, verbose_name='Subsector'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='code',
            field=models.CharField(max_length=10, verbose_name='Code'),
        ),
    ]
