# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0002_stock_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='target price')),
                ('stop_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='stop gain')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='stop loss')),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='limit')),
                ('action', models.TextField(blank=True, max_length=140, null=True, verbose_name='action')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='oparation date')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='creation date')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=22, verbose_name='amount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='stock value')),
                ('favorite', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='favorite')),
            ],
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.OperationType'),
        ),
        migrations.AddField(
            model_name='operation',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock'),
        ),
        migrations.AddField(
            model_name='experiencedata',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Operation'),
        ),
    ]
