# Generated by Django 2.0.6 on 2018-06-14 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='oparation date')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='creation date')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=22, verbose_name='amount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='stock value')),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('nickname', models.TextField(blank=True, max_length=100, null=True, verbose_name='nickname')),
                ('favorite', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='favorite')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExperienceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='oparation date')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='creation date')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=22, verbose_name='amount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='stock value')),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('nickname', models.TextField(blank=True, max_length=100, null=True, verbose_name='nickname')),
                ('favorite', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='favorite')),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='target price')),
                ('stop_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='stop gain')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='stop loss')),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='limit')),
                ('action', models.TextField(blank=True, max_length=140, null=True, verbose_name='action')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SellData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='oparation date')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='creation date')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=22, verbose_name='amount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='stock value')),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('nickname', models.TextField(blank=True, max_length=100, null=True, verbose_name='nickname')),
                ('favorite', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='favorite')),
                ('value', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='sell value')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
