# Generated by Django 2.0.6 on 2018-06-19 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selldata',
            name='value',
        ),
    ]
