# Generated by Django 2.0.6 on 2018-07-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20180715_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='favorite'),
        ),
    ]
