# Generated by Django 2.0.6 on 2018-06-24 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('operation', '0002_remove_selldata_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='buydata',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencedata',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selldata',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
            preserve_default=False,
        ),
    ]
