# Generated by Django 2.1.5 on 2019-06-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_operation'),
        ('operation', '0002_selldata_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selldata',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='operation_ptr',
        ),
        migrations.DeleteModel(
            name='SellData',
        ),
    ]
