# Generated by Django 3.0.6 on 2020-06-02 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_system', '0002_auto_20200602_1525'),
        ('operation', '0003_auto_20190621_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_system.Analysis'),
        ),
    ]
