# Generated by Django 2.0.6 on 2018-07-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_auto_20180724_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencedata',
            name='intent',
            field=models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1),
        ),
    ]
