# Generated by Django 2.0.6 on 2018-08-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_experiencedata_intent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencedata',
            name='intent',
            field=models.CharField(blank=True, choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1, null=True),
        ),
    ]
