# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20171219_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='archived',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='archived'),
        ),
    ]
