# Generated by Django 2.0.6 on 2018-10-18 18:16

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_auto_20180817_1940'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='buydata',
            managers=[
                ('boughts', django.db.models.manager.Manager()),
            ],
        ),
    ]
