# Generated by Django 2.0.6 on 2018-11-19 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0006_auto_20181018_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='date',
        ),
    ]
