# Generated by Django 2.0.6 on 2018-11-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_remove_operation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='executed',
            field=models.BooleanField(default=False, verbose_name='executed'),
        ),
    ]
