# Generated by Django 2.0.6 on 2018-11-30 17:37

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_operation_executed'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='buydata',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='selldata',
            managers=[
                ('solds', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='buydata',
            name='stop_gain',
        ),
        migrations.RemoveField(
            model_name='buydata',
            name='stop_loss',
        ),
        migrations.AddField(
            model_name='selldata',
            name='stop_gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='stop gain'),
        ),
        migrations.AddField(
            model_name='selldata',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='stop loss'),
        ),
    ]
