# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-01 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_buydata_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='nickname',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='nickname'),
        ),
    ]
