# Generated by Django 2.0.6 on 2018-06-13 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_operation_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='buydata',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='buydata',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='experiencedata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='experiencedata',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='id',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='operation',
        ),
        migrations.AddField(
            model_name='buydata',
            name='operation_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operation.Operation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencedata',
            name='operation_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operation.Operation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selldata',
            name='operation_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operation.Operation'),
            preserve_default=False,
        ),
    ]
