# Generated by Django 2.0.6 on 2018-06-13 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_auto_20180613_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydata',
            name='operation_ptr',
        ),
        migrations.RemoveField(
            model_name='experiencedata',
            name='operation_ptr',
        ),
        migrations.RemoveField(
            model_name='selldata',
            name='operation_ptr',
        ),
        migrations.AddField(
            model_name='buydata',
            name='operation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operation.Operation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiencedata',
            name='operation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operation.Operation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selldata',
            name='operation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operation.Operation'),
            preserve_default=False,
        ),
    ]
