# Generated by Django 2.0.6 on 2018-12-03 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_operation_execution_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='buydata',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.ExperienceData'),
        ),
        migrations.AddField(
            model_name='selldata',
            name='buy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.BuyData'),
        ),
    ]
