# Generated by Django 2.1.5 on 2019-01-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_auto_20181203_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='operation cost'),
        ),
    ]
