# Generated by Django 2.1.5 on 2019-01-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_operation_operation_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='operation_cost',
        ),
        migrations.AddField(
            model_name='operation',
            name='operation_kind',
            field=models.CharField(blank=True, choices=[('DT', 'Daytrade'), ('F', 'Fraction'), ('O', 'Ordinary')], max_length=2, null=True),
        ),
    ]
