# Generated by Django 2.1.5 on 2019-01-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_auto_20190118_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='operation_kind',
        ),
        migrations.AddField(
            model_name='operation',
            name='category',
            field=models.CharField(choices=[('DT', 'Daytrade'), ('O', 'Ordinary'), ('F', 'Fraction')], max_length=2, null=True),
        ),
    ]
