# Generated by Django 2.1.5 on 2019-01-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_auto_20190118_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.CharField(choices=[('DT', 'Daytrade'), ('O', 'Ordinary'), ('F', 'Fraction'), ('NA', 'Not yet Defined')], max_length=2, null=True),
        ),
    ]
