# Generated by Django 2.1.5 on 2019-02-12 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0015_auto_20190118_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='favorite',
            field=models.IntegerField(default=0, verbose_name='favorite'),
        ),
    ]
