# Generated by Django 2.1.5 on 2019-02-22 18:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0017_auto_20190213_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='operation',
            name='category',
            field=models.CharField(choices=[('DT', 'Daytrade'), ('O', 'Ordinary'), ('F', 'Fraction'), ('NA', 'Not yet Defined')], default='NA', max_length=2),
        ),
    ]
