# Generated by Django 2.1.5 on 2019-04-09 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_auto_20190409_1656'),
        ('notes', '0002_note_creation_date'),
        ('operation', '0018_auto_20190222_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencedata',
            name='operation_ptr',
        ),
        migrations.AlterField(
            model_name='buydata',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='experience.ExperienceData'),
        ),
        migrations.DeleteModel(
            name='ExperienceData',
        ),
    ]
