# Generated by Django 2.1.5 on 2019-06-13 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_creation_date'),
        ('operation', '0019_auto_20190409_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buydata',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='buydata',
            name='operation_ptr',
        ),
        migrations.AlterField(
            model_name='selldata',
            name='buy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buy.BuyData'),
        ),
        migrations.DeleteModel(
            name='BuyData',
        ),
    ]
