# Generated by Django 2.0.6 on 2018-10-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0006_auto_20181018_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=140, null=True, verbose_name='note')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Operation')),
            ],
        ),
    ]
