# Generated by Django 2.1.5 on 2019-06-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, max_length=140, null=True, verbose_name='note')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='creation date')),
            ],
        ),
    ]
