# Generated by Django 2.0.6 on 2018-12-18 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='creation date'),
            preserve_default=False,
        ),
    ]
