# Generated by Django 2.1.5 on 2019-06-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_initial'),
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='operation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Operation'),
        ),
    ]
