# Generated by Django 2.0.6 on 2018-12-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_auto_20181024_1349'),
        ('stock', '0002_auto_20181123_1945'),
        ('operation', '0011_auto_20181203_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(editable=False, verbose_name='creation date')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=22, verbose_name='amount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='stock value')),
                ('archived', models.BooleanField(default=False, verbose_name='archived')),
                ('nickname', models.TextField(blank=True, max_length=100, null=True, verbose_name='nickname')),
            ],
        ),
        migrations.CreateModel(
            name='PaperBuy',
            fields=[
                ('paperoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning.PaperOperation')),
                ('experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.ExperienceData')),
            ],
            bases=('learning.paperoperation',),
        ),
        migrations.CreateModel(
            name='PaperSell',
            fields=[
                ('paperoperation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning.PaperOperation')),
                ('stop_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='stop gain')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='stop loss')),
                ('buy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.BuyData')),
            ],
            bases=('learning.paperoperation',),
        ),
        migrations.AddField(
            model_name='paperoperation',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AddField(
            model_name='paperoperation',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.Stock'),
        ),
    ]
