# Generated by Django 2.0.6 on 2018-12-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papersell',
            name='buy',
        ),
        migrations.AddField(
            model_name='papersell',
            name='paper_buy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='learning.PaperBuy'),
        ),
    ]
