# Generated by Django 2.1.5 on 2019-06-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paperbuy',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='experience.ExperienceData'),
        ),
    ]
