# Generated by Django 2.1.5 on 2019-01-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20181228_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperoperation',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=22, verbose_name='price'),
        ),
    ]
