# Generated by Django 2.1.5 on 2019-04-09 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0003_auto_20190118_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperbuy',
            name='experience',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='experience.ExperienceData'),
        ),
    ]
