# Generated by Django 2.1.5 on 2019-06-14 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceData',
            fields=[
                ('operation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='operation.Operation')),
                ('target', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='target price')),
                ('stop_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='stop gain')),
                ('stop_loss', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='stop loss')),
                ('limit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='limit')),
                ('action', models.TextField(blank=True, max_length=140, null=True, verbose_name='action')),
                ('intent', models.CharField(blank=True, choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1, null=True)),
            ],
            bases=('operation.operation',),
        ),
    ]
