# Generated by Django 3.0.6 on 2020-05-18 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experience', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiencedata',
            name='estimated_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='estimated_date'),
        ),
    ]
