# Generated by Django 3.0.6 on 2020-05-31 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beginning', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='beginning')),
                ('end', models.DecimalField(blank=True, decimal_places=2, max_digits=22, null=True, verbose_name='end')),
            ],
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('indicator_kind', models.CharField(max_length=140, verbose_name='indicator kind')),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalAnalyze',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='comment')),
                ('analysis', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trade_system.Analysis')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_system.Indicator')),
            ],
        ),
        migrations.AddField(
            model_name='analysis',
            name='indicators',
            field=models.ManyToManyField(through='trade_system.TechnicalAnalyze', to='trade_system.Indicator'),
        ),
    ]
